name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: arduino/setup-protoc@v2
      -
        name: Build C# samples
        run: python build_all_csharp.py
      -
        name: Build Python samples
        run: python build_all_python.py
