name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: [linux, x64]
    container: znly/protoc:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build C# samples
        run: python build_all_csharp.py
      -
        name: Build Python samples
        run: python build_all_python.py
